name: practice
on: [push]
jobs:
  greeting-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello world!"
      - name: greeting javascript action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Parshant kumar"
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform 
          print(platform.processor())
        shell: python
  run-windows-commands:
    needs: ["run-shell-commands"]
    runs-on: windows-latest
    steps:
      - name: Directory Poweshell
        run: Get-Location      
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'